### ISSUE TITLE
字体文件许可证问题，等。

### ISSUE THREAD

**Issue by MY1L** [BienhCunShan/Nvshu-Font-Package#1]
发现 nvshu1.ttf 该字体有17.4MB之巨，不正常。打开看发现似乎是用微软自带宋体修改，包含几万个宋体字形，许可证\版权等处还写着中易公司。因此我把除了396个女书外所有有版权疑虑的字符全删，得6MB：[柳叶体女书.zip](https://github.com/BienhCunShan/Nvshu-Font-Package/files/6510712/default.zip)，其它没动。

另，该字体缺一个女书重复号？

**Comment by anonymousbone** [comment]
> 发现 nvshu1.ttf 该字体有17.4MB之巨，不正常。打开看发现似乎是用微软自带宋体修改，包含几万个宋体字形，许可证\版权等处还写着中易公司。因此我把除了396个女书外所有有版权疑虑的字符全删，得6MB：[柳叶体女书.zip](https://github.com/BienhCunShan/Nvshu-Font-Package/files/6510712/default.zip)，其它没动。
> 
> 另，该字体缺一个女书重复号？

thank you for fixed, nice job

**Comment by BienhCunShan** [comment]
是直接从宋体改的，所以其余字体都是宋体，不能商用，有版权风险。thanks for the job!
