### ISSUE TITLE
“多”“落”对应的字是否反了？“七”“人”是重复的？还有……

### ISSUE THREAD

**Issue by MY1L** [BienhCunShan/Nvshu-Font-Package#2]
我正在复刻柳叶体，才发现字体中存在一些问题以及“错字”（或者说异体字）🤔

其中“华啼安欢歌肉”六个字与统一码字形相差很大，我准备当作异体，用OT特性包纳。

**Comment by MY1L** [comment]
还有几个问题。
1. 似乎“杯”和“背”也对调了。
2. “几”对应的字可能有问题。
3. 书法家似为[胡欣](http://www.thurcacca.org/booksearch.html)。

**Comment by BienhCunShan** [comment]
谢谢反馈，书法家是胡欣，取得过许可了。这个字体包严格来说版权是有问题的，纯属个人爱好，不考虑商业应用。做的过程比较匆忙，只投入了一天的时间，所以有一些错误，感谢你的勘误！由于时间问题，以后也不会再更新了。

**Comment by MY1L** [comment]
了解了，不过你得在首页自述声明一下这些对应有误和许可证等问题，因为此前该字体已被许多人使用了，他们应该还不知道。
（顺带这是前几个月的报告，我上个月已做了一个没有这些问题的字体😂）
